use_frameworks!

target 'YYBaseClases_Example' do
  pod 'YYBaseClases', :path => '../'

  target 'YYBaseClases_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
